### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by ericanst** [Mayoogh/Arduino-Bluetooth-Basic#1]
I can find the paired devices on paireddevice-list , but I can't connect one of them. Does the app only fit bluetooth 2.0 (HC-05) not 4.0 devices (HC-08 or android phones). How to solve it ?

**Comment by Mayoogh** [comment]
Did you tried with different android device ?

**Comment by Mayoogh** [comment]
Closing issue since there is no response. 

Closing #1

**Comment by ericanst** [comment]
I tried, but it didn't work

**Comment by Mayoogh** [comment]
> I can find the paired devices on paired device-list, but I can't connect one of them. Does the app only fit Bluetooth 2.0 (HC-05) not 4.0 devices (HC-08 or android phones)? How to solve it?

HC-08 is a Bluetooth 4.0 low energy module(BLE), This application only supports SPP
