### ISSUE TITLE
Can't connect BLE bluetooth

### ISSUE THREAD

**Issue by ericanst** [Mayoogh/Arduino-Bluetooth-Basic#2]
This app can't connect ble bluetooth. It failed when I clicked the device in devicelist , it just showed " Is it a SPP device? , try again" . How can I fix it , please help me.

**Comment by ericanst** [comment]
I tried different phones, but all of these showed the same question : " Is it a SPP device? , try again";
and I noticed there were several people having this issue , they also didn't know how to solve it.
Is it  because of the difference of SPP and BLE ?

**Comment by Mayoogh** [comment]
This application does not support BLE pairing, try with SPP modules.
I am working on BLE application
