### ISSUE TITLE
Bluetooth connected but led pins does not light up

### ISSUE THREAD

**Issue by inspiritpanda** [Mayoogh/Arduino-Bluetooth-Basic#8]
I am trying to create a simple bluetooth circuit with led lights where it can connect to a mobile application and turn the led lights on/off remotely. i am using arduino mega 2560 and bluetooth HC-05 with led light in pin 13. i have followed most tutorials online for the schematic. (5v - 5v), (GND - GND), (RX - TX1 18), (TX - RX1 19).
![image](https://user-images.githubusercontent.com/73899695/98013011-c0fef880-1e34-11eb-9a19-ff3b6c3ccb54.png)

 i have tried few different codes which were also gotten online. 

```
int ledPin = 13;
int state = 0;
int flag = 0;

void setup() {
  pinMode(ledPin, OUTPUT);
  digitalWrite(ledPin, LOW);

  Serial.begin(9600); // Default connection rate for my BT module
}

void loop() {

  if (Serial.available() > 0) {
    state = Serial.read();
    flag = 0;
  }

  if (state == '0') {
    digitalWrite(ledPin, LOW);
    if (flag == 0) {
      Serial.println("LED: off");
      flag = 1;
    }
  }

  else if (state == '1') {
    digitalWrite(ledPin, HIGH);
    if (flag == 0) {
      Serial.println("LED: on");
      flag = 1;
    }
  }
}
```

Few applications that i have tried are ArduDroid by TechBitar, LED, Arduino Bluetooth app by HowtoMeChatronics and even tried making my own simple application by MIT app developer. all of them i am able to be connected to HC05 and disconnect them. however, the LED lights does not light up. I am not sure how to test if the bluetooth module can send/receive data from the phone application. 

Do let me know where is the error as i am getting the sources online and they seem to work with their set up.

**Comment by Mayoogh** [comment]
Hey @inspiritpanda 

Did you try sending input through the serial monitor?

Remove the tx rx connection and try sending `1` and `0`
![image](https://user-images.githubusercontent.com/16350186/99897066-5f57de80-2cbc-11eb-9427-ccad8e572e8c.png)

> I am not sure how to test if the Bluetooth module can send/receive data from the phone application.

Similarly, you can test this also with the serial monitor

**Comment by inspiritpanda** [comment]
Hello,
yes i tested with the tx and rx connection removed and typed in the commands in serial monitor and the led lights turned off and on. when i connected the bluetooth module, the red light on the hc-05 starts to blink slower at around 2secs interval which shows that it has been connected. but i still do not know what is the issue and why the lcd cannot be controlled via application. @Mayoogh

**Comment by Mayoogh** [comment]
Are you using a BLE device?
Try the following.
1.  Forget the paired Bluetooth device and pair again
2.  Double check Bluetooth serial connection ``TX to RX`` and ``RX to TX``
3.  After successful pairing the led blinking pattern on the Bluetooth module should change
4.  Check if values are showing on the serial monitor if the button is pressed (from the android device)
5.  Try with a different android device / Bluetooth module

**Comment by inspiritpanda** [comment]
Hi @Mayoogh 
yes, i am currently using a BLE device and i have also tried with another phone as well but it still doesnt work.
when i pressed the button on the android device, there is no value showing on the serial monitor. which means the phone is not communicating with arduino?

**Comment by Mayoogh** [comment]
It's a limitation of this application. Which I have already mentioned in the [readme](https://github.com/Mayoogh/Arduino-Bluetooth-Basic/blob/master/README.md) .

Currently, this application does not support  **BLE (Bluetooth Low Energy)** devices. only works with **SPP (Serial Port Profile)**  devices.
This bug won't be fixed branch. BLE support will be added in the future release.

Hence closing.

**Comment by Mayoogh** [comment]
It's a limitation of this application. Which I have already mentioned in the [readme](https://github.com/Mayoogh/Arduino-Bluetooth-Basic/blob/master/README.md) .

Currently, this application does not support  **BLE (Bluetooth Low Energy)** devices. only works with **SPP (Serial Port Profile)**  devices.
BLE support will be added in the future release.

Hence closing.

**Comment by inspiritpanda** [comment]
Just to confirm, isnt android devices supporting SPP and BLE as well? @Mayoogh

**Comment by Mayoogh** [comment]
> Just to confirm, isn't android devices supporting SPP and BLE as well? @Mayoogh

Yes, android supports both SPP and BLE. The BLE support is currently not integrated with this app

**Comment by inspiritpanda** [comment]
then in this case why am i still not able to use the mobile app to control the led light? @Mayoogh

**Comment by Mayoogh** [comment]
In general, Android devices support BLE but this particular app currently does not support BLE. There are many apps already available with BLE supports.

**Comment by inspiritpanda** [comment]
hi i have solved this issue. realised that for arduino mega if i am using tx1 and rx1, i would need to change the code from Serial to Serial1 instead.
